In [2]:
import numpy as np
print(np.array([1,2,3]))
arr = np.array([[1,2,3], [4,5,6]])
print(arr.ndim)
print(arr[0, 0:1], arr[0, 2])

[1 2 3]
2
[1] 3


### data types in numpy
##### i - integer
##### b - boolean
##### u - unsigned integer
##### f - float
##### c - complex float
##### m - timedelta
##### M - datetime
##### O - object
##### S - string
##### U - unicode string
##### V - fixed chunk of memory for other type ( void )
##### Use astype() function for changing pre-existing data types


In [3]:
another = arr.copy()
another[0, 2] = 4
print(another)
print(another.shape)

[[1 2 4]
 [4 5 6]]
(2, 3)


In [15]:
array = np.array([1,2,3,4,5,6,7,8,9])
Two_D_array = array.reshape(3,3)
print(Two_D_array)
Three_D_array = array.reshape(3, 3, 1)
# looping in a 3d array
for one_array in Three_D_array:
    for another_array in one_array:
        for Literally_another in another_array:
            print(Literally_another)
print()
# or we can do this
for one_val in np.nditer(Three_D_array):
    print(one_val)
print(Three_D_array.base)
# passing -1 into reshape() means converting it into a 1 dimensional array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9

1
2
3
4
5
6
7
8
9
[1 2 3 4 5 6 7 8 9]


In [4]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
    print(x)
# enumerting in an array
for index, x in np.ndenumerate(arr):
    print(index, x)

b'1'
b'2'
b'3'
1
3
5
7
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Concatenating arrays

In [14]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[4],[5],[6]])
new = np.concatenate((arr1, arr2), axis=1)
print(new)

[[1 4]
 [2 5]
 [3 6]]


# Stacking arrays

In [17]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,2,3], [4,5,6]])
new = np.stack((arr1, arr2), axis=2)
print(new)
new = np.vstack((arr1, arr2))
print(new)
new = np.hstack((arr1, arr2))
print(new)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Splitting arrays

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
for x in np.nditer(newarr):
    print(x)
print(newarr[0])


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)
# can use hsplit() instead of array_split() for splitting horizontally

[array([1, 2]), array([3, 4]), array([5, 6])]
(array(1), array(3), array(5))
(array(2), array(4), array(6))
[1 2]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### Searching in an array

In [8]:
arr = np.array([1,2,3,4,5,6])
find = np.where(arr % 2 == 0)
print(find)

a = np.searchsorted(arr, 3, side='right')
print(a)
insertion_points = np.searchsorted(arr, [0,7,8,9], side='right')
print(insertion_points)

(array([1, 3, 5], dtype=int64),)
3
[0 6 6 6]


#### sorting can be done by using the sort() function which sorts arrays in place meaning a 2d or 3d array will be solved in place without changing positions

## Filtering an array

In [9]:
arr = np.array([1,2,3,4,5])
filtered = [False, False, True, True, False]
print(arr[filtered])
# fiteration based on an condition
new = []
for element in arr:
    if element >= 3: new.append(True)
    else: new.append(False)
print(arr[new])
print(arr[arr > 4])

[3 4]
[3 4 5]
[5]


### Numpy ufunc() methods

In [12]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(np.add(x, y))

def myadd(x, y):
    return x + y

myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1,2,3,4], [5,6,7,8]))

[ 6  8 10 12]
[6 8 10 12]


### ufunc() methods, basic arithmetic ones: are incompleted without np. 
##### add() :- takes two or more arrays and returns a single array containing the sum in vertical axis.
##### subtract() :- takes two or more arrays and returns a single array containing the difference in vertical axis.
##### multiply() :- takes two or more arrays and returns a single array containing the product in vertical axis.
##### divide() :- takes two or more arrays and returns a single array containing the division in vertical axis.
##### remainder() or mod() :- takes two arrays and returns the remainders in vertical axis.
##### power() :- takes two arrays and returns an array where the first array is base and second array is exponent.
##### divmod() :- takes two arrays and returns two arrays where first is the quotient and second is the remainder.
##### absolute() takes a single array and returns a single array where each value is the absolute value from the first array in the same position.
##### truncate() takes a single array and returns a truncated single array.
##### fix() takes a single array and returns a truncated single array.
##### around() takes a single array and a number to which it rounds each value amd returns a single array.
##### floor() takes a single array and rounds up to closest whole number.
##### ceil() takes a single array and rounds down to closest whole number.
